In [1]:
import numpy as np
test_list = [[1, 4, 5, 8], [1, 4, 5]]
#np.array(test_list, float) # ValueError

In [2]:
import numpy as np
test_array = np.array([1, 4, 5, 8], float)
print(test_array)

[1. 4. 5. 8.]


In [3]:
import numpy as np #numpy 라이브러리 호출
tmp = [[1, 4, 5, 8], [21, 23, 15, 11]] #리스트 형식의 2차 배열
test_array = np.array(tmp, float)#2차원 배열 및 형 변환
test_array #'test_array＇출력

array([[ 1.,  4.,  5.,  8.],
       [21., 23., 15., 11.]])

In [4]:
print(type(tmp))
print(type(tmp[1][3]))

<class 'list'>
<class 'int'>


In [5]:
print(type(test_array[0]))
print(type(test_array[1][3]))

<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [6]:
test_array = np.array([[0,1,2], [3,4,5], [6,7,8]]) 
print(test_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
print(test_array.dtype)
print(test_array.ndim)
print(test_array.shape)
print(test_array.strides)

int32
2
(3, 3)
(12, 4)


In [8]:
vector = np.array([1, 4, 5, "8"], float)
print(vector)

[1. 4. 5. 8.]


In [9]:
print(vector.dtype)   #자료형
print(vector.ndim)    #차원=랭크
print(vector.shape)   #구조
print(vector.strides) #크기 

float64
1
(4,)
(8,)


In [10]:
matrix = np.array([[1,2,5,8], [1,2,5,8], [1,2,5,8]])
print(matrix)

[[1 2 5 8]
 [1 2 5 8]
 [1 2 5 8]]


In [11]:
print(matrix.dtype)   #자료형
print(matrix.ndim)    #차원=랭크
print(matrix.shape)   #구조
print(matrix.strides) #크기 

int32
2
(3, 4)
(16, 4)


In [12]:
#원소 개수
print(vector.size)
print(matrix.size)

4
12


In [13]:
#원소의 크기(단위:바이트)
print(vector.itemsize)
print(matrix.itemsize)

8
4


In [14]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [15]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [16]:
print(x)

[[1 2 5 8]
 [1 2 5 8]]


In [17]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [18]:
#x.reshape(2,2)

In [19]:
x.reshape(4,2) #but x의 모양은 그대로임S

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [20]:
x.reshape(2,4) #but x의 모양은 그대로임

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [22]:
x.flatten() #but x의 모양은 그대로임

array([1, 2, 5, 8, 1, 2, 5, 8])

In [23]:
x = np.array(range(6)).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
x[0][0]

0

In [25]:
x[0,2]

2

In [26]:
x[0, 1] = 100
x

array([[  0, 100,   2],
       [  3,   4,   5]])

In [27]:
x = np.array(range(10)).reshape(2,5)
x[:,2:] # 전체 행의 2열 이상

array([[2, 3, 4],
       [7, 8, 9]])

In [28]:
x[1,1:3] # 1행의 1열 ~ 2열

array([6, 7])

In [29]:
x[1:3] # 1행 ~ 2행의 전체

array([[5, 6, 7, 8, 9]])

In [30]:
x[:,[1,3,4]]

array([[1, 3, 4],
       [6, 8, 9]])

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [33]:
np.arange(0, 5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [34]:
np.ones(shape=(5,2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [35]:
np.zeros(shape=(2,2), dtype=np.float32)


array([[0., 0.],
       [0., 0.]], dtype=float32)

In [36]:
np.empty(shape=(2,4), dtype=np.float32)

array([[0.0000e+00, 1.4013e-45, 0.0000e+00, 6.1657e-44],
       [1.6199e-42, 0.0000e+00, 1.0762e-42, 4.5912e-41]], dtype=float32)

In [37]:
np.random.uniform(0, 5, 10)

array([3.33551494, 1.38320987, 4.15745917, 0.51566579, 4.70055157,
       0.09387903, 2.25588338, 1.3113139 , 1.97073189, 0.77662494])

In [38]:
np.random.normal(0, 2, 10)

array([-1.01473452, -0.1825785 , -0.2998138 ,  1.22781   ,  2.39680808,
        0.52875355,  1.68428174, -1.1591668 ,  0.79698402, -0.44948178])

In [39]:
import numpy as np
test_array = np.arange(1, 13) #벡터
test_array.sum()

78

In [40]:
test_array = test_array.reshape(3,4)
test_array.sum(axis=0) #np.sum(test_array, axis=0)

array([15, 18, 21, 24])

In [41]:
test_array.sum(axis=1)#np.sum(test_array, axis=1)

array([10, 26, 42])

In [42]:
test_array.mean(axis=1) # axis=1 축을 기준으로 평균 연산

array([ 2.5,  6.5, 10.5])

In [43]:
np.std(test_array) # 전체 값에 대한 표준편차 연산

3.452052529534663

In [44]:
test_array.std(axis=0)# axis=0 축을 기준으로 표준편차 연산

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [45]:
np.sqrt(test_array) # 각 요소에 제곱근 연산 수행

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [46]:
import numpy as np #numpy라이브러리호출

tmp= [[1, 4, 5, 8], [21, 23, 15, 11]] #리스트형식의2차배열
test_array = np.array(tmp, float)#2차원배열및형변환

print(test_array) #'test_array'출력

print(test_array.var())
print(test_array.var(0))#axis=0
print(test_array.var(1))#axis=1

[[ 1.  4.  5.  8.]
 [21. 23. 15. 11.]]
56.75
[100.    90.25  25.     2.25]
[ 6.25 22.75]


In [47]:
v1 = np.array([1, 2, 3]) 
v2 = np.array([4, 5, 6])
np.vstack((v1, v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6])

In [49]:
v1 = v1.reshape(-1, 1)
v2 = v2.reshape(-1, 1)
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
x = np.arange(1, 7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
x+x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [52]:
x-x

array([[0, 0, 0],
       [0, 0, 0]])

In [53]:
x/x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
x**x #x^x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [55]:
x_1 = np.arange(1, 7).reshape(2,3)
x_2 = np.arange(1, 7).reshape(3,2)
print(x_1)
print(x_2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [56]:
x_1.dot(x_2)

array([[22, 28],
       [49, 64]])

In [57]:
x = np.arange(1, 10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
x + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [59]:
x - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [60]:
x = np.arange(1, 13).reshape(4,3)
v = np.arange(10 , 40 , 10)
x + v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [61]:
import numpy as np
x = np.array([4, 3, 2, 6, 8, 5]) 
x > 3

array([ True, False, False,  True,  True,  True])

In [62]:
x = np.array([1, 3, 0])
y = np.array([2, 1, 7])
x > y

array([False,  True, False])

In [63]:
x = np.array([4, 3, 2, 6, 8, 5]) 
(x > 3).all()

False

In [64]:
(x > 3).any()

True

In [65]:
x = np.array([4, 6, 7, 3, 2])
x > 5

array([False,  True,  True, False, False])

In [66]:
np.where(x>5)

(array([1, 2], dtype=int64),)

In [67]:
x = np.array([4, 6, 7, 3, 2])
np.where(x>5 , 10, 20)

array([20, 10, 10, 20, 20])

In [68]:
x = np.array([4, 6, 7, 3, 2])
x > 3

array([ True,  True,  True, False, False])

In [69]:
cond = x > 3
x[cond] # x[x>3]

array([4, 6, 7])

In [70]:
x = np.array([4, 6, 7, 3, 2])
np.argsort(x)

array([4, 3, 0, 1, 2], dtype=int64)

In [71]:
np.argmax(x)

2

In [72]:
np.argmin(x)

4