In [1]:
import numpy as np
test_array = np.array([1, 4, 5, 8], float)
print(test_array)

[1. 4. 5. 8.]


In [2]:
import numpy as np # Import the NumPy library
tmp = [[1, 4, 5, 8], [21, 23, 15, 11]] # A two-dimensional nested list
test_array = np.array(tmp, float) # Create a 2D array and convert its elements to float
test_array # Display 'test_array'

array([[ 1.,  4.,  5.,  8.],
       [21., 23., 15., 11.]])

In [3]:
print(type(tmp))
print(type(tmp[1][3]))

<class 'list'>
<class 'int'>


In [4]:
print(type(test_array[0]))
print(type(test_array[1][3]))

<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [5]:
test_array = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(test_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
print(test_array.dtype)    # Data type of the elements
print(test_array.ndim)     # Rank = Number of dimensions
print(test_array.shape)    # Array shape
print(test_array.strides)  # Memory step size along each axis (in bytes)

int64
2
(3, 3)
(24, 8)


In [7]:
vector = np.array([1, 4, 5, "8"], float)
print(vector)

[1. 4. 5. 8.]


In [8]:
print(vector.dtype)    # Data type of the elements
print(vector.ndim)     # Number of dimensions = Rank
print(vector.shape)    # Array shape
print(vector.strides)  # Memory step size along each axis (in bytes)

float64
1
(4,)
(8,)


In [9]:
matrix = np.array([[1,2,5,8], [1,2,5,8], [1,2,5,8]])
print(matrix)

[[1 2 5 8]
 [1 2 5 8]
 [1 2 5 8]]


In [10]:
print(matrix.dtype)
print(matrix.ndim)
print(matrix.shape)
print(matrix.strides)

int64
2
(3, 4)
(32, 8)


In [63]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [64]:
x.reshape(2,2)

ValueError: cannot reshape array of size 8 into shape (2,2)

In [13]:
x.reshape(4,2) #But the shape of x remains unchanged.

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [14]:
x.reshape(2,4) #But the shape of x remains unchanged.

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [16]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [17]:
print(x)

[[1 2 5 8]
 [1 2 5 8]]


In [18]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [19]:
x.flatten() #But the shape of x remains unchanged.

array([1, 2, 5, 8, 1, 2, 5, 8])

In [20]:
x = np.array(range(6)).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
x[0][0]

np.int64(0)

In [22]:
x[0,2]

np.int64(2)

In [23]:
x[0, 1] = 100
x

array([[  0, 100,   2],
       [  3,   4,   5]])

In [24]:
x = np.array(range(10)).reshape(2,5)
x[:,2:] # All rows, from column index 2 onward

array([[2, 3, 4],
       [7, 8, 9]])

In [25]:
x[1,1:3] # Row index 1, from column index 1 to 2

array([6, 7])

In [26]:
x[1:3] # Row indices 1 to 2, all columns

array([[5, 6, 7, 8, 9]])

In [27]:
x[:,[1,3,4]]

array([[1, 3, 4],
       [6, 8, 9]])

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [30]:
np.arange(0, 5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [31]:
np.random.uniform(0, 5, 10)

array([2.22653982, 1.87349371, 0.46232086, 3.96863224, 1.27203179,
       4.69041757, 4.22076688, 4.9903622 , 2.61619184, 1.9737728 ])

In [32]:
np.random.normal(0, 2, 10)

array([ 2.45465226,  2.62026319, -2.44646652, -0.28725936, -1.70216633,
        0.09464561, -2.72511828, -2.98142959, -2.29049294,  1.99234502])

In [33]:
import numpy as np
test_array = np.arange(1, 13) #vector
test_array.sum()

np.int64(78)

In [34]:
test_array = test_array.reshape(3,4)
test_array.sum(axis=0) #np.sum(test_array, axis=0)

array([15, 18, 21, 24])

In [35]:
test_array.sum(axis=1)#np.sum(test_array, axis=1)

array([10, 26, 42])

In [36]:
test_array.mean(axis=1) # Calculate the mean for each row.

array([ 2.5,  6.5, 10.5])

In [37]:
np.std(test_array) # Calculate the standard deviation of all values.

np.float64(3.452052529534663)

In [38]:
test_array.std(axis=0)# Calculate the standard deviation for each column.

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [39]:
np.sqrt(test_array) # Calculate the square root of each element.

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [40]:
import numpy as np #numpy라이브러리호출

tmp= [[1, 4, 5, 8], [21, 23, 15, 11]] #리스트형식의2차배열
test_array = np.array(tmp, float)#2차원배열및형변환

print(test_array) #'test_array'출력

print(test_array.var())
print(test_array.var(0))#axis=0
print(test_array.var(1))#axis=1

[[ 1.  4.  5.  8.]
 [21. 23. 15. 11.]]
56.75
[100.    90.25  25.     2.25]
[ 6.25 22.75]


In [41]:
x = np.arange(1, 7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
x+x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [43]:
x-x

array([[0, 0, 0],
       [0, 0, 0]])

In [44]:
x/x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
x**x #x^x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [46]:
x_1 = np.arange(1, 7).reshape(2,3)
x_2 = np.arange(1, 7).reshape(3,2)
print(x_1)
print(x_2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [47]:
x = np.arange(1, 10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
x + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [49]:
x - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [50]:
x = np.arange(1, 13).reshape(4,3)
v = np.arange(10 , 40 , 10)
x + v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [51]:
import numpy as np
x = np.array([4, 3, 2, 6, 8, 5])
x > 3

array([ True, False, False,  True,  True,  True])

In [52]:
x = np.array([1, 3, 0])
y = np.array([2, 1, 7])
x > y

array([False,  True, False])

In [53]:
x = np.array([4, 3, 2, 6, 8, 5])
(x > 3).all()

np.False_

In [54]:
(x > 3).any()

np.True_

In [55]:
x = np.array([4, 6, 7, 3, 2])
x > 5

array([False,  True,  True, False, False])

In [56]:
np.where(x>5)

(array([1, 2]),)

In [57]:
x = np.array([4, 6, 7, 3, 2])
np.where(x>5 , 10, 20)

array([20, 10, 10, 20, 20])

In [58]:
x = np.array([4, 6, 7, 3, 2])
x > 3

array([ True,  True,  True, False, False])

In [59]:
cond = x > 3
x[cond] # x[x>3]

array([4, 6, 7])

In [60]:
x = np.array([4, 6, 7, 3, 2])
np.argsort(x)

array([4, 3, 0, 1, 2])

In [61]:
np.argmax(x)

np.int64(2)

In [62]:
np.argmin(x)

np.int64(4)