In [2]:
import numpy as np #numpy 라이브러리 호출
tmp = [[1, 4, 5, 8], [21, 23, 15, 11]] #리스트 형식의 2차 배열
test_array = np.array(tmp, float)#2차원 배열 및 형 변환
test_array #'test_array＇출력

array([[ 1.,  4.,  5.,  8.],
       [21., 23., 15., 11.]])

In [3]:
print(type(tmp))
print(type(tmp[1][3]))

<class 'list'>
<class 'int'>


In [4]:
print(type(test_array[0]))
print(type(test_array[1][3]))

<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [5]:
test_array = np.array([[0,1,2], [3,4,5], [6,7,8]]) 
print(test_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
print(test_array.dtype)    # 데이터의 자료형
print(test_array.ndim)     # 랭크=차원
print(test_array.shape)    # 구조
print(test_array.strides)  # 메모리 간격(Byte 단위)

int32
2
(3, 3)
(12, 4)


In [7]:
vector = np.array([1, 4, 5, "8"], float)
print(vector)

[1. 4. 5. 8.]


In [8]:
print(vector.dtype)   #자료형
print(vector.ndim)    #차원=랭크
print(vector.shape)   #구조
print(vector.strides) #크기 

float64
1
(4,)
(8,)


In [9]:
matrix = np.array([[1,2,5,8], [1,2,5,8], [1,2,5,8]])
print(matrix)

[[1 2 5 8]
 [1 2 5 8]
 [1 2 5 8]]


In [10]:
print(matrix.dtype)   #자료형
print(matrix.ndim)    #차원=랭크
print(matrix.shape)   #구조
print(matrix.strides) #크기 

int32
2
(3, 4)
(16, 4)


In [11]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [12]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [13]:
print(x)

[[1 2 5 8]
 [1 2 5 8]]


In [14]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [15]:
x.reshape(2,2)

ValueError: cannot reshape array of size 8 into shape (2,2)

In [16]:
x.reshape(4,2) #but x의 모양은 그대로임

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [17]:
x.reshape(2,4) #but x의 모양은 그대로임

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x

In [18]:
x.flatten() #but x의 모양은 그대로임

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
x = np.array(range(6)).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
x[0][0]

0

In [21]:
x[0,2]

2

In [22]:
x[0, 1] = 100
x

array([[  0, 100,   2],
       [  3,   4,   5]])

In [23]:
x = np.array(range(10)).reshape(2,5)
x[:,2:] # 전체 행의 2열 이상

array([[2, 3, 4],
       [7, 8, 9]])

In [24]:
x[1,1:3] # 1행의 1열 ~ 2열\

array([6, 7])

In [25]:
x[1:3] # 1~2행 전체=> 2행은 없으므로 1행만

array([[5, 6, 7, 8, 9]])

In [26]:
x[:,[1,3,4]]

array([[1, 3, 4],
       [6, 8, 9]])

In [27]:
np.random.uniform(0, 5, 10)

array([3.99218848, 1.12834725, 0.52320393, 3.66578792, 1.94059295,
       0.85268423, 1.39359704, 2.24595216, 0.57084327, 4.68859502])

In [28]:
np.random.normal(0, 2, 10)

array([ 5.04308393, -2.58207225,  0.54053703, -0.86716111, -1.98320148,
       -2.6740966 ,  0.04522157,  3.01093191,  0.75199858,  0.21864375])

In [29]:
import pandas as pd# (1) pandas 모듈 호출

#(2)데이터 URL을 변수 data_url에 넣기
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'

#(3) csv 데이터 로드
df_data = pd.read_csv(data_url, sep='\s+', header = None)

In [30]:
from pandas import DataFrame

raw_data = {'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
'last_name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze'], 
'age': [42, 52, 36, 24, 73], 
'city': ['San Francisco', 'Baltimore', 'Miami', 'Douglas', 'Boston']}

df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'city'])
df

,first_name,last_name,age,city
0,Jason,Miller,42,San Francisco
1,Molly,Jacobson,52,Baltimore
2,Tina,Ali,36,Miami
3,Jake,Milner,24,Douglas
4,Amy,Cooze,73,Boston


In [31]:
DataFrame(raw_data, columns = ["age", "city"])

,age,city
0,42,San Francisco
1,52,Baltimore
2,36,Miami
3,24,Douglas
4,73,Boston


In [32]:
DataFrame(raw_data, 
          columns = ["first_name","last_name","age", "city", "debt"])

,first_name,last_name,age,city,debt
0,Jason,Miller,42,San Francisco,NaN
1,Molly,Jacobson,52,Baltimore,NaN
2,Tina,Ali,36,Miami,NaN
3,Jake,Milner,24,Douglas,NaN
4,Amy,Cooze,73,Boston,NaN


In [33]:
file = 'https://raw.githubusercontent.com/prof-dana/Lecture-Code/refs/heads/main/AdvancedMachineLearning/data/comp-data.csv'

df_data = pd.read_csv(file) # csv 데이터 로드
df = pd.DataFrame(df_data)
df

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
1,320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
4,121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000
5,132971,"Williamson, Schumm and Hettinger",89403 Casimer Spring,Jeremieburgh,Arkansas,62785,150000,120000,35000
6,145068,Casper LLC,340 Consuela Bridge Apt. 400,Lake Gabriellaton,Mississipi,18008,62000,120000,70000
7,205217,Kovacek-Johnston,91971 Cronin Vista Suite 601,Deronville,RhodeIsland,53461,145000,95000,35000
8,209744,Champlin-Morar,26739 Grant Lock,Lake Juliannton,Pennsylvania,64415,70000,95000,35000
9,212303,Gerhold-Maggio,366 Maggio Grove Apt. 998,North Ras,Idaho,46308,70000,120000,35000


In [34]:
df.head()#default는 5개

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
1,320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
4,121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000


In [35]:
df.head(3).T

,0,1,2
account,211829,320563,648336
name,"Kerluke, Koepp and Hilpert",Walter-Trantow,"Bashirian, Kunde and Price"
street,34456 Sean Highway,1311 Alvis Tunnel,62184 Schamberger Underpass Apt. 231
city,New Jaycob,Port Khadijah,New Lilianland
state,Texas,NorthCarolina,Iowa
postal-code,28752,38365,76517
Jan,10000,95000,91000
Feb,62000,45000,120000
Mar,35000,35000,35000


In [36]:
df.tail(4)

,account,name,street,city,state,postal-code,Jan,Feb,Mar
11,231907,Hahn-Moore,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
12,242368,"Frami, Anderson and Donnelly",182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
13,268755,Walsh-Haley,2624 Beatty Parkways,Goodwinmouth,RhodeIsland,31919,55000,120000,35000
14,273274,McDermott PLC,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000


In [37]:
df[["name","city","state"]][7:13]

,name,city,state
7,Kovacek-Johnston,Deronville,RhodeIsland
8,Champlin-Morar,Lake Juliannton,Pennsylvania
9,Gerhold-Maggio,North Ras,Idaho
10,"Goodwin, Homenick and Jerde",Rosaberg,Tenessee
11,Hahn-Moore,Norbertomouth,NorthDakota
12,"Frami, Anderson and Donnelly",East Davian,Iowa


In [38]:
df.iloc[7:13, [1,3,4]]

,name,city,state
7,Kovacek-Johnston,Deronville,RhodeIsland
8,Champlin-Morar,Lake Juliannton,Pennsylvania
9,Gerhold-Maggio,North Ras,Idaho
10,"Goodwin, Homenick and Jerde",Rosaberg,Tenessee
11,Hahn-Moore,Norbertomouth,NorthDakota
12,"Frami, Anderson and Donnelly",East Davian,Iowa


In [39]:
df = df.drop(1) #행 1번 삭제
df.head()

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
4,121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000
5,132971,"Williamson, Schumm and Hettinger",89403 Casimer Spring,Jeremieburgh,Arkansas,62785,150000,120000,35000


In [40]:
import numpy as np
df.drop(np.arange(4,10), inplace=True)#inplace 원본 데이터프레임에서 바로 삭제
df

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
10,214098,"Goodwin, Homenick and Jerde",649 Cierra Forks Apt. 078,Rosaberg,Tenessee,47743,45000,120000,55000
11,231907,Hahn-Moore,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
12,242368,"Frami, Anderson and Donnelly",182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
13,268755,Walsh-Haley,2624 Beatty Parkways,Goodwinmouth,RhodeIsland,31919,55000,120000,35000
14,273274,McDermott PLC,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000


In [41]:
df.drop("account",axis=1).head(3)  # account 열 제거

,name,street,city,state,postal-code,Jan,Feb,Mar
0,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
2,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000


In [42]:
df.drop(["account", "name"], axis=1,inplace = True) # account, name 열 바로 삭제
df.head(3)

,street,city,state,postal-code,Jan,Feb,Mar
0,34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
2,62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000


In [43]:
df[df['Jan']>= 150000]

,street,city,state,postal-code,Jan,Feb,Mar
11,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
12,182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
14,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000


In [44]:
df[(df['Jan']>= 10000) & (df['state'] == 'Iowa')]

,street,city,state,postal-code,Jan,Feb,Mar
2,62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
12,182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
